 export const dataFake = [
        {
        "updated": 1719320334155,
        "country": "Afghanistan",
        "countryInfo": {
            "_id": 4,
            "iso2": "AF",
            "iso3": "AFG",
            "lat": 33,
            "long": 65,
            "flag": "https://disease.sh/assets/img/flags/af.png"
        },
        "cases": 234174,
        "todayCases": 0,
        "deaths": 7996,
        "todayDeaths": 0,
        "recovered": 211080,
        "todayRecovered": 0,
        "active": 15098,
        "critical": 0,
        "casesPerOneMillion": 5746,
        "deathsPerOneMillion": 196,
        "tests": 1390730,
        "testsPerOneMillion": 34125,
        "population": 40754388,
        "continent": "Asia",
        "oneCasePerPeople": 174,
        "oneDeathPerPeople": 5097,
        "oneTestPerPeople": 29,
        "activePerOneMillion": 370.46,
        "recoveredPerOneMillion": 5179.32,
        "criticalPerOneMillion": 0
    },
    {
        "updated": 1719320334148,
        "country": "Albania",
        "countryInfo": {
            "_id": 8,
            "iso2": "AL",
            "iso3": "ALB",
            "lat": 41,
            "long": 20,
            "flag": "https://disease.sh/assets/img/flags/al.png"
        },
        "cases": 334863,
        "todayCases": 0,
        "deaths": 3605,
        "todayDeaths": 0,
        "recovered": 330233,
        "todayRecovered": 0,
        "active": 1025,
        "critical": 0,
        "casesPerOneMillion": 116825,
        "deathsPerOneMillion": 1258,
        "tests": 1941032,
        "testsPerOneMillion": 677173,
        "population": 2866374,
        "continent": "Europe",
        "oneCasePerPeople": 9,
        "oneDeathPerPeople": 795,
        "oneTestPerPeople": 1,
        "activePerOneMillion": 357.59,
        "recoveredPerOneMillion": 115209.32,
        "criticalPerOneMillion": 0
    },
    {
        "updated": 1719320334151,
        "country": "Algeria",
        "countryInfo": {
            "_id": 12,
            "iso2": "DZ",
            "iso3": "DZA",
            "lat": 28,
            "long": 3,
            "flag": "https://disease.sh/assets/img/flags/dz.png"
        },
        "cases": 272010,
        "todayCases": 0,
        "deaths": 6881,
        "todayDeaths": 0,
        "recovered": 183061,
        "todayRecovered": 0,
        "active": 82068,
        "critical": 0,
        "casesPerOneMillion": 5998,
        "deathsPerOneMillion": 152,
        "tests": 230960,
        "testsPerOneMillion": 5093,
        "population": 45350148,
        "continent": "Africa",
        "oneCasePerPeople": 167,
        "oneDeathPerPeople": 6591,
        "oneTestPerPeople": 196,
        "activePerOneMillion": 1809.65,
        "recoveredPerOneMillion": 4036.61,
        "criticalPerOneMillion": 0
    },
]
